name: Build and Deploy Multiple Services

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # или 'adopt', если предпочитаете
          java-version: '21'

      - name: Build Service 1
        run: |
          cd service1
          mvn clean install

      - name: Build Service 2
        run: |
          cd service2
          mvn clean install

      - name: Build Service 3
        run: |
          cd service3
          mvn clean install